# Generated by Django 4.0.4 on 2022-08-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_id', models.CharField(max_length=240)),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
            ],
        ),
    ]
